name: Build HDF5 & JHDF5

on:
  push:
    branches: [ "main", "dev*", "*-cicd" ]
  pull_request:
    branches: [ "main", "dev*", "*-cicd" ]

jobs:
  build-hdf5-linux:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
    
    steps:

    - name: Check presence of tools
      shell: bash
      run: |
        set -ex
        zstd --help
        xz --help
        tar --help
        gcc --version
    
    - name: Setup JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
        java-package: 'jdk'
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set environment variables for HDF5 build
      run: |
        echo "UPLOAD_DEBUG_ARCHIVE=true" >> $GITHUB_ENV
        echo "REPLACE_JNI=0" >> $GITHUB_ENV
        echo "JHDF5_ADDITIONAL_GCC_FLAGS=-O3 -march=haswell -mtune=znver3 -Wl,--exclude-libs,ALL" >> $GITHUB_ENV
        JAVA_PATH="$(which java)"
        JAVA_BIN_PATH=$(dirname "${JAVA_PATH}")
        JAVA_HOME_PATH=$(dirname "${JAVA_BIN_PATH}")
        if [[ -z ${JAVA_HOME+x} ]]; then
          echo "JAVA_HOME=${JAVA_HOME_PATH}" >> $GITHUB_ENV
        fi
        echo "JVM_INCLUDE_PATH=${JAVA_HOME_PATH}/include" >> $GITHUB_ENV
        
    - name: Display env
      run: env
      
    - name: Compile HDF5 + Plugins (Linux)
      working-directory: ./source/c
      run: ./compile_hdf5_linux_amd64.sh
      
    - name: JHDF5 (Linux)
      continue-on-error: true
      working-directory: ./source/c
      run: ./compile_linux_amd64.sh

    - name: Compress build environment for debugging
      working-directory: . # Repository root
      continue-on-error: true
      if: env.UPLOAD_DEBUG_ARCHIVE == 'true'
      run: | 
        tar -c . | zstd -z -T0 --adapt -v -o archive.tar.zst
        
    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      continue-on-error: true
      if: env.UPLOAD_DEBUG_ARCHIVE == 'true'
      with:
        name: debug_archive
        path: |
          archive.tar.zst

    - name: Release debug archive
      uses: marvinpinto/action-automatic-releases@latest
      continue-on-error: true
      if: env.UPLOAD_DEBUG_ARCHIVE == 'true'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: debug
        prerelease: true
        title: "Debugging archive"
        files: |
          **/*.tar.zst
